# Generated by Django 5.2 on 2025-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Your Signature Here', max_length=140),
        ),
    ]
