# Generated by Django 5.2 on 2025-04-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_alter_post_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Love One Another as I Have Loved You', max_length=140),
        ),
    ]
